// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/contact.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/login.tsx";
import * as $4 from "./routes/register.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LoginPageForm.tsx";
import * as $$2 from "./islands/RegisterPageForm.tsx";
import * as $$3 from "./islands/TestMotionComponent.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/contact.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/login.tsx": $3,
    "./routes/register.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LoginPageForm.tsx": $$1,
    "./islands/RegisterPageForm.tsx": $$2,
    "./islands/TestMotionComponent.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
